# -*- coding: utf-8 -*-
"""scan_pending_mentions.py — find every thread in the current inbox that has a
comment directed at Enough1122 which I have NOT replied to yet.

Why this exists: GitHub's `reason == "mention"` is unreliable. It is set when the
*notification* was generated by a mention, so a thread whose latest activity is a
bot triage comment still shows up as `mention`, while genuine unanswered replies
to my reviews (author responds in-thread quoting my comment) can sit for weeks
without being flagged. This script ignores `reason` entirely and instead:

    pending := comments after my LAST comment on the thread
               whose body contains "Enough1122"
               and whose author is not Enough1122

That is the only criterion that actually means "someone is waiting on me".

Usage:
    python scan_pending_mentions.py            # read drafts/_inbox_triage.json
    python scan_pending_mentions.py --refresh  # re-pull notifications first

Writes drafts/_pending_mentions.json and prints a TSV.

Note: run `gh_inbox_triage.py` first if drafts/_inbox_triage.json is stale.
"""
import json
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from urllib.request import Request, urlopen

TOK_PATH = r'C:\Users\admin\AppData\Local\hermes\.env'
REPO = 'NousResearch/hermes-agent'
ME = 'Enough1122'
BASE = 'https://api.github.com'
TRIAGE = r'D:\Hermes\projects\github-tools\drafts\_inbox_triage.json'
OUT = r'D:\Hermes\projects\github-tools\drafts\_pending_mentions.json'

tok = [l.split('=', 1)[1].strip()
       for l in open(TOK_PATH, encoding='utf-8') if l.startswith('GITHUB_TOKEN=')][0]
H = {'User-Agent': 'Hermes-Agent', 'Accept': 'application/vnd.github+json',
     'Authorization': 'Bearer ' + tok}


def g_all(url):
    """Page through a list endpoint.

    GitHub returns 403 for *secondary* rate limits (request burst / too many
    concurrent calls) even when the primary 5000/hour quota is untouched, so a
    403 here must be retried with backoff rather than treated as fatal.
    """
    out = []
    while url:
        for attempt in range(4):
            try:
                r = urlopen(Request(url, headers=H), timeout=30)
                break
            except Exception as e:
                if '403' in str(e) or '429' in str(e):
                    time.sleep(2 * (attempt + 1) ** 2)
                    continue
                print('PAGE-ERR %s' % str(e)[:60], file=sys.stderr)
                return out
        else:
            print('PAGE-ERR giving up after retries: %s' % url[:80], file=sys.stderr)
            return out
        out.extend(json.loads(r.read()))
        link = r.headers.get('Link', '')
        url = None
        for part in link.split(','):
            if 'rel="next"' in part:
                url = part[part.index('<') + 1:part.index('>')]
    return out


def scan(n):
    """Return (pr_number, total_comments, idx_of_my_last_comment, [pending...])."""
    ic = g_all('%s/repos/%s/issues/%d/comments?per_page=100' % (BASE, REPO, n))
    rc = g_all('%s/repos/%s/pulls/%d/comments?per_page=100' % (BASE, REPO, n))
    allc = [('issue', c) for c in ic] + [('review', c) for c in rc]
    allc.sort(key=lambda x: x[1]['created_at'])
    mine = [i for i, (_, c) in enumerate(allc)
            if (c.get('user') or {}).get('login') == ME]
    last = mine[-1] if mine else -1
    pend = []
    for i, (kind, c) in enumerate(allc):
        if i <= last:
            continue
        if (c.get('user') or {}).get('login') == ME:
            continue
        if ME not in (c.get('body') or ''):
            continue
        pend.append({
            'kind': kind, 'comment_id': c['id'], 'user': (c.get('user') or {}).get('login'),
            'created_at': c['created_at'],
            'body': (c.get('body') or '')[:600],
            'html': c.get('html_url'),
        })
    return n, len(allc), last, pend


def main():
    rows = json.load(open(TRIAGE, encoding='utf-8'))
    nums = sorted({int(r['url'].rsplit('/', 1)[-1])
                   for r in rows if '/pulls/' in (r['url'] or '')})
    print('scanning %d threads from %s' % (len(nums), TRIAGE), flush=True)
    found = {}
    # 6 workers, not 12: 12 triggers GitHub's secondary (burst) rate limit on a
    # 50-thread inbox, which silently drops pages and produces false "0 pending".
    with ThreadPoolExecutor(max_workers=6) as ex:
        for n, tot, last, pend in ex.map(scan, nums):
            if pend:
                found[n] = {'total_comments': tot, 'my_last_index': last, 'pending': pend}
    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(found, f, ensure_ascii=False, indent=1)
    print('threads with pending @%s: %d' % (ME, len(found)))
    for n in sorted(found):
        for p in found[n]['pending']:
            print('%d\t%s\t%s\t%s\t%s' % (n, p['kind'], p['user'], p['created_at'], p['html']))
    print('saved: ' + OUT)


if __name__ == '__main__':
    main()
