"""Coarse-rank the survivor issues so deep triage is spent on the few that can
actually ship, and so obviously-unfixable ones are dropped without an agent.

This is a SCREEN, not a verdict. Every keep/drop reason is recorded so a human
(or the final report) can audit why something was dropped. The deep stage must
still verify source code, claim status, and open-PR collision before any fix.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

SCRATCH = Path("C:/Users/admin/AppData/Local/hermes/cache/scratch")
INDEX = SCRATCH / "issue_detail_index.json"
OUT = SCRATCH / "issue_coarse_rank.json"

# Labels that disqualify regardless of how good the prose looks.
BAD_LABELS = {
    "duplicate", "invalid", "needs-repro", "needs-decision", "wontfix",
    "question", "stale", "help-wanted", "wont-fix", "documentation",
}
GOOD_LABELS = {"type/bug", "type/security"}

# Feature / preference phrasing: not defects.
FEATURE_RE = re.compile(
    r"\b(?:feature request|would be (?:nice|great|good)|please add|can you add|"
    r"add support|support for|would love|i'd like|request(?:ing)? (?:a|an|the) (?:feature|option)|"
    r"proposal|suggestion|enhancement|ideally|would be helpful|nice to have)\b",
    re.I,
)

# A real bug report usually has some observed-vs-expected evidence.
EVIDENCE_RE = re.compile(
    r"(?:steps to reproduce|reproduce(?:d|s| step)?|repro|expected (?:behaviour|behavior|result|output)|"
    r"actual(?:ly)?(?: produces| returns| shows| gives| outputs)|traceback|"
    r"stack trace|instead of|but instead|unexpectedly|on \w+ \d+\.\d+)",
    re.I,
)

# Signals that the report is thin / not actionable.
THIN_RE = re.compile(
    r"\b(?:doesn'?t work|not working|broken|breaks|fails)\b(?![^.]*\b(?:because|when|after|error|exception)\b)",
    re.I,
)

# Someone says they are on it (a claim even if not assigned).
CLAIM_RE = re.compile(
    r"\b(?:i(?:'m| am) (?:working on|looking at|taking|on it)|"
    r"working on this|take(?:n)? this|assigned to me|i(?:'ll| will) (?:fix|handle|look))\b",
    re.I,
)
# ...unless they also stepped back / released the claim.
RELEASE_RE = re.compile(
    r"\b(?:stepping back|stepped back|releas(?:e|ed|ing) (?:my |the )?(?:claim|assignment)?|"
    r"not going to (?:fix|work|pursue)|abandon(?:ing|ed)|hand(?:ing|ed) (?:this|it) (?:off|over)|"
    r"no longer|superseded)\b",
    re.I,
)

SEVERITY = {"p0": 3, "p1": 3, "p2": 2, "p3": 1, "critical": 3, "high": 2, "medium": 1, "low": 0}


def score(r: dict) -> tuple[int, list[str]]:
    s, why = 0, []
    labels = set(r["labels"])
    title = r.get("title", "")
    body = r.get("body", "")
    blob = f"{title}\n{body}"
    all_comments = "\n".join(c["body"] for c in r.get("comments", []))

    # severity
    for lbl, w in SEVERITY.items():
        if lbl in labels:
            s += w * 3
            why.append(f"severity:{lbl}")
            break

    # evidence density
    if EVIDENCE_RE.search(blob):
        s += 4
        why.append("has-evidence")
    # body length is a weak proxy for detail
    n = len(body)
    if n > 1200:
        s += 2
        why.append("detailed-body")
    elif n > 400:
        s += 1
    elif n < 120:
        s -= 3
        why.append("thin-body")

    # specificity: names a file/symbol/function
    if re.search(r"`[A-Za-z_][\w./]{3,}`", blob):
        s += 2
        why.append("names-symbol")
    if re.search(r"\b\w+\.(?:py|ts|tsx|js|jsx|md|yaml|yml|json)\b", blob):
        s += 2
        why.append("names-file")

    # defect-shaped language
    if re.search(r"\b(?:silently|ignored|ignores|drop(?:s|ped)?|never (?:reaches|passed|sent)|"
                 r"wrong|incorrect|mismatch|off-by-one|truncat\w*|data loss|corrupt\w*|"
                 r"infinite loop|hang(?:s|ing)?|deadlock|race condition|leak)\b", blob, re.I):
        s += 3
        why.append("defect-language")

    # negatives
    if FEATURE_RE.search(blob) and not re.search(r"\b(?:bug|regression|broken|should not|expected)\b", blob, re.I):
        s -= 6
        why.append("feature-request")
    if THIN_RE.search(blob) and not EVIDENCE_RE.search(blob):
        s -= 3
        why.append("vague")
    if not labels & GOOD_LABELS:
        s -= 5
        why.append("not-bug-label")
    if labels & BAD_LABELS:
        s -= 8
        why.append("bad-label:" + ",".join(sorted(labels & BAD_LABELS)))

    # claim handling: active claim is disqualifying, released claim is not
    if CLAIM_RE.search(all_comments):
        if RELEASE_RE.search(all_comments):
            s += 1
            why.append("claim-released")
        else:
            s -= 10
            why.append("active-claim")

    # maintainer / bot triage noise
    if re.search(r"This was generated by AI|automated triage|maintainer", all_comments, re.I):
        s -= 2

    # discussion volume: often means "needs maintainer decision"
    if len(r.get("comments", [])) >= 6:
        s -= 2
        why.append("long-thread")

    return s, why


def main() -> int:
    rows = json.loads(INDEX.read_text(encoding="utf-8"))
    for r in rows:
        r["score"], r["why"] = score(r)
    rows.sort(key=lambda r: (-r["score"], -len(r.get("body", ""))))

    keep = [r for r in rows if r["score"] >= 4]
    drop = [r for r in rows if r["score"] < 4]

    OUT.write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"indexed {len(rows)}  |  keep(score>=4): {len(keep)}  drop: {len(drop)}\n")
    print(f"{'#':>7} {'score':>5} {'c':>3}  {'why':<44} title")
    for r in rows:
        mark = "KEEP" if r["score"] >= 4 else "drop"
        print(f"#{r['number']:>6} {r['score']:>5} {len(r.get('comments',[])):>3} {mark}  "
              f"{','.join(r['why'])[:44]:<44} {r['title'][:78]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
